spring.application.name=incident-management

spring.datasource.url=jdbc:postgresql://localhost:5432/incidencias_db
spring.datasource.username=postgres
spring.datasource.password=7825

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

app.upload.dir=uploads

spring.mail.host=
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true